#!/usr/bin/env python3
"""Known athletics domains for D1 baseball programs.

Domains are not derivable from school names - Wake Forest is godeacs.com, LSU is lsusports.net,
Arizona State is thesundevils.com - so discovery from Wikipedia and name patterns tops out around
half the field. This seed list is tried first, which makes the common case a single request.

Nothing here is trusted on faith. sidearm_scrape.py verifies every fetched roster against the
TrackMan pitcher names before accepting it, so an entry that is wrong or stale fails verification
and is discarded rather than attaching the wrong heights to real pitchers. That makes it safe to
include a domain that is only probably right.
"""

SEEDS = {
    "Air Force": "goairforcefalcons.com", "Akron": "gozips.com", "Alabama": "rolltide.com",
    "Alabama A&M": "aamusports.com", "Alabama St.": "bamastatesports.com",
    "Abilene Christian": "acusports.com", "Alcorn": "alcornsports.com",
    "App State": "appstatesports.com", "Arizona": "arizonawildcats.com",
    "Arizona St.": "thesundevils.com", "Arkansas": "arkansasrazorbacks.com",
    "Arkansas St.": "astateredwolves.com", "Ark.-Pine Bluff": "uapblionsroar.com",
    "Army West Point": "goarmywestpoint.com", "Auburn": "auburntigers.com",
    "Austin Peay": "letsgopeay.com", "Ball St.": "ballstatesports.com",
    "Baylor": "baylorbears.com", "Bellarmine": "athletics.bellarmine.edu",
    "Belmont": "belmontbruins.com", "Bethune-Cookman": "bcuathletics.com",
    "Binghamton": "bubearcats.com", "Boston College": "bceagles.com",
    "Bowling Green": "bgsufalcons.com", "Bradley": "bradleybraves.com",
    "Brown": "brownbears.com", "Bryant": "bryantbulldogs.com", "Bucknell": "bucknellbison.com",
    "Butler": "butlersports.com", "BYU": "byucougars.com", "Cal": "calbears.com",
    "Cal Poly": "gopoly.com", "Cal St. Fullerton": "fullertontitans.com",
    "Cal St. Northridge": "gomatadors.com", "California Baptist": "cbulancers.com",
    "Campbell": "gocamels.com", "Canisius": "gogriffs.com", "Central Ark.": "ucasports.com",
    "Central Conn. St.": "ccsubluedevils.com", "Central Mich.": "cmuchippewas.com",
    "Charleston So.": "csusports.com", "Charlotte": "charlotte49ers.com",
    "Chicago St.": "gochicagostatecougars.com", "Cincinnati": "gobearcats.com",
    "Clemson": "clemsontigers.com", "Coastal Carolina": "goccusports.com",
    "Col. of Charleston": "cofcsports.com", "Colgate": "gocolgateraiders.com",
    "Columbia": "gocolumbialions.com", "Coppin St.": "coppinstatesports.com",
    "Cornell": "cornellbigred.com", "Creighton": "gocreighton.com",
    "CSU Bakersfield": "gorunners.com", "CSUN": "gomatadors.com",
    "Dallas Baptist": "dbupatriots.com", "Dartmouth": "dartmouthsports.com",
    "Davidson": "davidsonwildcats.com", "Dayton": "daytonflyers.com",
    "Delaware": "bluehens.com", "Delaware St.": "dsuhornets.com", "Duke": "goduke.com",
    "East Carolina": "ecupirates.com", "East Tenn. St.": "etsubucs.com",
    "Eastern Ill.": "eiupanthers.com", "Eastern Ky.": "ekusports.com",
    "Eastern Mich.": "emueagles.com", "Elon": "elonphoenix.com", "Evansville": "gopurpleaces.com",
    "Fairfield": "fairfieldstags.com", "Fairleigh Dickinson": "fduknights.com",
    "FGCU": "fgcuathletics.com", "FIU": "fiusports.com", "Fla. Atlantic": "fausports.com",
    "Florida": "floridagators.com", "Florida A&M": "famuathletics.com",
    "Florida St.": "seminoles.com", "Fordham": "fordhamsports.com",
    "Fresno St.": "gobulldogs.com", "Furman": "furmanpaladins.com",
    "Ga. Southern": "gseagles.com", "Gardner-Webb": "gwusports.com",
    "George Mason": "gomason.com", "George Washington": "gwsports.com",
    "Georgetown": "guhoyas.com", "Georgia": "georgiadogs.com", "Georgia St.": "georgiastatesports.com",
    "Georgia Tech": "ramblinwreck.com", "Gonzaga": "gozags.com", "Grambling": "gsutigers.com",
    "Grand Canyon": "gculopes.com", "Hawaii": "hawaiiathletics.com", "High Point": "highpointpanthers.com",
    "Hofstra": "gohofstra.com", "Holy Cross": "goholycross.com", "Houston": "uhcougars.com",
    "Houston Christian": "hcuhuskies.com", "Illinois": "fightingillini.com",
    "Illinois St.": "goredbirds.com", "Incarnate Word": "uiwcardinals.com",
    "Indiana": "iuhoosiers.com", "Indiana St.": "gosycamores.com", "Iona": "icgaels.com",
    "Iowa": "hawkeyesports.com", "Jackson St.": "gojsutigers.com",
    "Jacksonville": "judolphins.com", "Jacksonville St.": "jsugamecocksports.com",
    "James Madison": "jmusports.com", "Kansas": "kuathletics.com", "Kansas St.": "kstatesports.com",
    "Kennesaw St.": "ksuowls.com", "Kent St.": "kentstatesports.com",
    "Kentucky": "ukathletics.com", "La Salle": "goexplorers.com", "Lafayette": "goleopards.com",
    "Lamar University": "lamarcardinals.com", "Le Moyne": "lemoynedolphins.com",
    "Lehigh": "lehighsports.com", "Liberty": "liberty.edu", "Lipscomb": "lipscombsports.com",
    "Little Rock": "lrtrojans.com", "LIU": "liuathletics.com", "Long Beach St.": "longbeachstate.com",
    "Longwood": "longwoodlancers.com", "Louisiana": "ragincajuns.com",
    "Louisiana Tech": "latechsports.com", "Louisville": "gocards.com", "LSU": "lsusports.net",
    "Loyola Marymount": "lmulions.com", "Maine": "goblackbears.com", "Manhattan": "gojaspers.com",
    "Marist": "goredfoxes.com", "Marshall": "herdzone.com", "Maryland": "umterps.com",
    "Massachusetts": "umassathletics.com", "McNeese": "mcneesesports.com",
    "Memphis": "gotigersgo.com", "Mercer": "mercerbears.com", "Merrimack": "merrimackathletics.com",
    "Miami (FL)": "hurricanesports.com", "Miami (OH)": "miamiredhawks.com",
    "Michigan": "mgoblue.com", "Michigan St.": "msuspartans.com", "Middle Tenn.": "goblueraiders.com",
    "Milwaukee": "mkepanthers.com", "Minnesota": "gophersports.com", "Mississippi St.": "hailstate.com",
    "Mississippi Val.": "mvsusports.com", "Missouri": "mutigers.com", "Missouri St.": "missouristatebears.com",
    "Monmouth": "monmouthhawks.com", "Morehead St.": "msueagles.com", "Mount St. Mary's": "mountathletics.com",
    "Murray St.": "goracers.com", "Navy": "navysports.com", "NC State": "gopack.com",
    "Nebraska": "huskers.com", "Nevada": "nevadawolfpack.com", "New Mexico": "golobos.com",
    "New Mexico St.": "nmstatesports.com", "New Orleans": "unoprivateers.com",
    "Niagara": "purpleeagles.com", "Nicholls": "geauxcolonels.com", "NJIT": "njithighlanders.com",
    "Norfolk St.": "nsuspartans.com", "North Ala.": "roarlions.com", "North Carolina": "goheels.com",
    "North Dakota St.": "gobison.com", "North Florida": "unfospreys.com", "North Texas": "meangreensports.com",
    "Northeastern": "nuhuskies.com", "Northern Colo.": "uncbears.com", "Northern Ill.": "niuhuskies.com",
    "Northern Ky.": "nkunorse.com", "Northwestern": "nusports.com", "Northwestern St.": "nsudemons.com",
    "Notre Dame": "und.com", "Oakland": "goldengrizzlies.com", "Ohio": "ohiobobcats.com",
    "Ohio St.": "ohiostatebuckeyes.com", "Oklahoma": "soonersports.com", "Oklahoma St.": "okstate.com",
    "Old Dominion": "odusports.com", "Ole Miss": "olemisssports.com", "Omaha": "omavs.com",
    "Oral Roberts": "oruathletics.com", "Oregon": "goducks.com", "Oregon St.": "osubeavers.com",
    "Pacific": "pacifictigers.com", "Penn": "pennathletics.com", "Penn St.": "gopsusports.com",
    "Pepperdine": "pepperdinewaves.com", "Pittsburgh": "pittsburghpanthers.com",
    "Portland": "portlandpilots.com", "Prairie View": "pvpanthers.com", "Presbyterian": "gobluehose.com",
    "Princeton": "goprincetontigers.com", "Purdue": "purduesports.com",
    "Purdue Fort Wayne": "gomastodons.com", "Queens (NC)": "queensathletics.com",
    "Quinnipiac": "gobobcats.com", "Radford": "radfordathletics.com", "Rhode Island": "gorhody.com",
    "Rice": "riceowls.com", "Richmond": "richmondspiders.com", "Rider": "gobroncs.com",
    "Rutgers": "scarletknights.com", "Sacramento St.": "hornetsports.com",
    "Sacred Heart": "sacredheartpioneers.com", "Saint Joseph's": "sjuhawks.com",
    "Saint Louis": "slubillikens.com", "Saint Mary's (CA)": "smcgaels.com",
    "Saint Peter's": "saintpeterspeacocks.com", "Sam Houston": "gobearkats.com",
    "Samford": "samfordsports.com", "San Diego": "usdtoreros.com", "San Diego St.": "goaztecs.com",
    "San Francisco": "usfdons.com", "San Jose St.": "sjsuspartans.com",
    "Santa Clara": "santaclarabroncos.com", "Seattle U": "goseattleu.com", "Seton Hall": "shupirates.com",
    "Siena": "sienasaints.com", "SIUE": "siuecougars.com", "South Ala.": "usajaguars.com",
    "South Carolina": "gamecocksonline.com", "South Dakota St.": "gojacks.com",
    "South Fla.": "gousfbulls.com", "Southeast Mo. St.": "gosoutheast.com",
    "Southeastern La.": "lionsports.net", "Southern California": "usctrojans.com",
    "Southern Ill.": "siusalukis.com", "Southern Miss": "southernmiss.com",
    "Southern U.": "gojagsports.com", "SFA": "sfajacks.com", "St. Bonaventure": "gobonnies.com",
    "St. John's (NY)": "redstormsports.com", "St. Thomas (MN)": "tommiesports.com",
    "Stanford": "gostanford.com", "Stetson": "gohatters.com", "Stonehill": "stonehillskyhawks.com",
    "Stony Brook": "stonybrookathletics.com", "Tarleton St.": "tarletonsports.com",
    "TCU": "gofrogs.com", "Temple": "owlsports.com", "Tennessee": "utsports.com",
    "Tennessee St.": "tsutigers.com", "Tennessee Tech": "ttusports.com", "Texas": "texassports.com",
    "Texas A&M": "12thman.com", "A&M-Corpus Christi": "goislanders.com",
    "Texas St.": "txstatebobcats.com", "Texas Tech": "texastech.com", "The Citadel": "citadelsports.com",
    "Toledo": "utrockets.com", "Towson": "towsontigers.com", "Troy": "troytrojans.com",
    "Tulane": "tulanegreenwave.com", "UAB": "uabsports.com", "UC Davis": "ucdavisaggies.com",
    "UC Irvine": "ucirvinesports.com", "UC Riverside": "gohighlanders.com",
    "UC San Diego": "ucsdtritons.com", "UC Santa Barbara": "ucsbgauchos.com",
    "UCF": "ucfknights.com", "UCLA": "uclabruins.com", "UIC": "uicflames.com",
    "UMBC": "umbcretrievers.com", "UMass Lowell": "goriverhawks.com", "UNC Asheville": "uncabulldogs.com",
    "UNC Greensboro": "uncgspartans.com", "UNC Wilmington": "uncwsports.com", "UNLV": "unlvrebels.com",
    "USC Upstate": "upstatespartans.com", "UT Arlington": "utamavs.com",
    "UT Martin": "utmsports.com", "UT Rio Grande Valley": "goutrgv.com", "Utah": "utahutes.com",
    "Utah Tech": "utahtechtrailblazers.com", "Utah Valley": "gouvu.com", "UTSA": "goutsa.com",
    "Valparaiso": "valpoathletics.com", "Vanderbilt": "vucommodores.com", "VCU": "vcuathletics.com",
    "Villanova": "villanova.com", "Virginia": "virginiasports.com", "Virginia Tech": "hokiesports.com",
    "VMI": "vmikeydets.com", "Wagner": "wagnerathletics.com", "Wake Forest": "godeacs.com",
    "Washington": "gohuskies.com", "Washington St.": "wsucougars.com", "Weber St.": "weberstatesports.com",
    "West Virginia": "wvusports.com", "Western Caro.": "catamountsports.com",
    "Western Ill.": "goleathernecks.com", "Western Ky.": "wkusports.com",
    "Western Mich.": "wmubroncos.com", "Wichita St.": "goshockers.com", "William & Mary": "tribeathletics.com",
    "Winthrop": "winthropeagles.com", "Wofford": "woffordterriers.com", "Wright St.": "wsuraiders.com",
    "Xavier": "goxavier.com", "Yale": "yalebulldogs.com", "Youngstown St.": "ysusports.com",
    # baseballr spells some schools differently than the entries above; same sites, other names
    "California": "calbears.com", "DBU": "dbupatriots.com", "ETSU": "etsubucs.com",
    "FDU": "fduknights.com", "Hartford": "hartfordhawks.com", "Harvard": "gocrimson.com",
    "LMU (CA)": "lmulions.com", "Lindenwood": "lindenwoodlions.com",
    "Mercyhurst": "hurstathletics.com", "N.C. A&T": "ncataggies.com", "NIU": "niuhuskies.com",
    "South Alabama": "usajaguars.com", "Southern Ind.": "gousieagles.com",
    "Southern Miss.": "southernmiss.com", "Texas Southern": "tsusports.com",
    "UAlbany": "ualbanysports.com", "UConn": "uconnhuskies.com", "UIW": "uiwcardinals.com",
    "ULM": "ulmwarhawks.com", "UMES": "easternshorehawks.com", "UNCW": "uncwsports.com",
    "UTRGV": "goutrgv.com", "West Ga.": "uwgathletics.com",
}
